### ISSUE TITLE
failing build due to missing create-env.sh?

### ISSUE THREAD

**Issue by sbassi** [biochunan/esmfold-docker-image#2]
**Describe the bug**
When building the docker (both manually and using the script) I get this:

```
zsh: can't open input file: /home/vscode/create-env.sh
The command '/bin/sh -c zsh /home/vscode/create-env.sh' returned a non-zero code: 127
```
**To Reproduce**

**Expected behavior**
I cd into the GH directory and run the script *./build-image.sh* or by running any variation of *docker build .*

**Screenshots**
<img width="878" alt="Screen Shot 2024-04-09 at 12 19 58 AM" src="https://github.com/biochunan/esmfold-docker-image/assets/238517/5347682e-7126-4fc7-8caf-daf62b5e3f63">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04 (Linux esmpytorchdocker 5.13.0-1022-azure #26~20.04.1-Ubuntu SMP Thu Apr 7 19:42:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

**Additional context**
This is an Azure VM, not sure if this is relevant. In the screenshot you can see the directory content, the required file is there.

**Comment by biochunan** [comment]
Hi @sbassi ! Thanks for submitting the issue. 

It looks like you modified the Dockerfile for your use case. Did you change the non-root user name? My scripts assumed the non-root user to be `vscode`, and `create-env.sh` also uses the `vscode` user. If you have changed or removed the user `vscode`, that might lead to the file not found error. 

Could you share the command you used for building the image? 

Finally, could you also try to build the image without any cache and print out the full logging info? e.g. like below: 
```sh
cd /path/to/esmfold-docker-image
docker build --no-cache --progress=plain -t esmfold:test . > build.log 2>&1 
```

By the way, I also updated the conda environments required for `openfold` and `esm`. The previous version `0.0.1` has issues with `torch` which I solved in the latest version 0.0.3. I recommend to try the latest version (simply pull from the main branch).

**Comment by sbassi** [comment]
hello biochunan. Thank you for your answer. I didn't changed the Dockerfile, and now I ran it using your command:

```
azureuser@esmpytorchdocker:~/esmfold-docker-image$ docker build --no-cache --progress=plain -t esmfold:test . > build.log 2>&1
```

And here is the log: https://gist.github.com/sbassi/1d7e9ee53443e4d5344adaa0ef0d6cd9

I also wander if there is a compiled image on dockerhub for this in case I can't make my own build.

**Comment by biochunan** [comment]
Hi @sbassi, Thanks for making a pull request! I will close this now, as you mentioned that adding permission solves the access problem. 

Dockerhub is a good suggestion; I will create one with the latest version.

**Comment by biochunan** [comment]
Hi @sbassi, the images are now pushed onto Dockerhub at [biochunan/esmfold-image](https://hub.docker.com/r/biochunan/esmfold-image/tags).
